### ISSUE TITLE
Analog drift

### ISSUE THREAD

**Issue by molnara** [MrX-8B/MiSTer-Arcade-FoodFight#1]
I am using a Logitech F710 2.4g wireless gamepad.  I am experiencing joystick analog drift.  This is not present in the Sinistar arcade core which also supports 49-way (analog core support).  I don't have any other controllers with an analog stick to test, so I'm just trying out different core that I know have analog support.

**Comment by MrX-8B** [comment]
Thank you for the report.

There is something i would like you to try, but when the game starts and the demo screen starts to move, slowly rotate the analog stick a few times, then try to play the game.
This is still useful during the game, so if you feel it's wrong, try it anytime.

If that doesn't work, let me know again.

**Comment by molnara** [comment]
OK, slowly rotating fixed the issue!  Thank you!  I was rotating too fast when I was initially calibrating.
